Custom data importers to the tracking pipeline
RichieHakim/ROICaT pull request #382
Opened 2024-12-23 19:17 UTC by dyf

2025-01-09 21:43 UTC, RichieHakim requested changes
Looks good. Passing in a non-JSON serializable item into the params dict is not ideal, but I'm happy to allow it for your use case. Are you sure there isn't a way for you to use the builtin Data_roicat class approach?

Only change required is adding the gif frame rate param to the util default params.

Thank you! Well done.

2025-01-09 21:43 UTC, RichieHakim commented on roicat/pipelines.py
> +        data = params['data_loading']['data_custom']
This makes me a bit nervous. I think I intended for the params to always be JSON serializable. This would break that assumption. I'm happy to include it for you if you want though.

2025-01-09 21:43 UTC, RichieHakim commented on roicat/pipelines.py
> +def pipeline_tracking(params: dict) -> tuple:
ty

2025-01-09 21:43 UTC, RichieHakim commented on roicat/pipelines.py
> +    assert data.check_completeness(verbose=False)['tracking'], f"Data object is missing attributes necessary for tracking."
good

2025-01-09 21:43 UTC, RichieHakim commented on roicat/pipelines.py
> +    if params['alignment']['fit_nonrigid']['method']:
perfect

2025-01-09 21:43 UTC, RichieHakim commented on roicat/util.py
> +                'data_custom': None
Would be nice to have a commented line on how this argument works and that it expects an actual Data_roicat object, which is not serializable.

2025-01-09 21:43 UTC, RichieHakim commented on roicat/pipelines.py
> +            frameRate=params['results_saving']['gif_frame_rate'],
CHANGE REQUIRED: I don't see this added to the util defaults.

2025-01-09 21:43 UTC, RichieHakim commented on roicat/pipelines.py
> +        helpers.save_gif(
these are great, ty

2025-01-13 23:40 UTC, dyf commented on roicat/pipelines.py
> +        data = params['data_loading']['data_custom']
Yes I wondered about that too. The alternative is that the tracking class has a custom optional argument. I'm fine with that if you prefer.

2025-01-15 03:06 UTC, RichieHakim commented on roicat/pipelines.py
> +        data = params['data_loading']['data_custom']
That's as great option I didn't consider. Just throw a `if custom_data is not None` at like line 53, and skip all the `params['data_loading']['data_kind']` checking. In the function docstring we should make sure it is clear what the form of the `custom_data` object needs to be. Consider any more assertions for confirming the object is valid. Feel free to implement any amount of it and assign me to do the rest.

2025-01-15 13:58 UTC, dyf commented on roicat/pipelines.py
> +        data = params['data_loading']['data_custom']
Great, I'll do this today.

2025-01-15 20:41 UTC, dyf commented on roicat/pipelines.py
> +            frameRate=params['results_saving']['gif_frame_rate'],
added below

2025-01-15 20:44 UTC, dyf commented
@RichieHakim take another look.

2025-01-15 22:08 UTC, RichieHakim approved these changes
looks good to me

2025-01-15 22:08 UTC, merged